# Generated by Django 3.0 on 2024-02-10 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=100)),
                ('homogeneity', models.CharField(max_length=100)),
                ('energy', models.CharField(max_length=100)),
                ('dissimilarity', models.CharField(max_length=100)),
                ('correlation', models.CharField(max_length=100)),
                ('contrast', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dieasename', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=300)),
                ('pin', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('housename', models.CharField(max_length=100)),
                ('houseno', models.CharField(max_length=100)),
                ('mobileno', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=300)),
                ('pin', models.CharField(max_length=100)),
                ('housename', models.CharField(max_length=100)),
                ('houseno', models.CharField(max_length=100)),
                ('mobileno', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symtoms', models.CharField(max_length=500)),
                ('DISEASE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Diease')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fromtime', models.CharField(max_length=30)),
                ('totime', models.CharField(max_length=30)),
                ('DOCTOR', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review', models.CharField(max_length=1000)),
                ('Rating', models.FloatField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('DOCTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Doctor')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeedback', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('USERNAME', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Login'),
        ),
        migrations.CreateModel(
            name='Compliant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('reply', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('message', models.CharField(max_length=2000)),
                ('FROMID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromid', to='myapp.Login')),
                ('TOID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toid', to='myapp.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=10)),
                ('SCHEDULE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Schedule')),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
    ]
