# Generated by Django 5.0.2 on 2024-02-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_appointment_id_alter_chat_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptoms',
            name='symtoms',
        ),
        migrations.AddField(
            model_name='symptoms',
            name='symptoms',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
