# Generated by Django 5.0.2 on 2024-03-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='diease',
            name='image',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
