# Generated by Django 5.0.2 on 2024-03-29 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_appoinmentreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoinmentreview',
            name='Rating',
        ),
    ]
